import { Product } from './product';

export const productList: Product[] = [
    {
        Id : 1,
        txt_product_name : 'pizza',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'food',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '309',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 2,
        txt_product_name : 'Burgar',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'food',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '103',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 3,
        txt_product_name : 'pant',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'dress',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '345',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 4,
        txt_product_name : 'shirt',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'dress',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '1200',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 5,
        txt_product_name : 'computer',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'electrical',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '1000',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 6,
        txt_product_name : 'headset',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'electrical',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '800',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
    {
        Id : 7,
        txt_product_name : 'pizza',
        url_image : '',
        txt_seller : 'jeo',
        num_product_variant : '1',
        num_product_category : 'food',
        txt_pack_type : '',
        slt_returnable : 'yes',
        num_price : '600',
        num_discount : '12',
        num_offer_price : '140',
        num_total_price : '150',
        num_dscount_fromseller : '10',
        num_stock_foronline : '3',
        num_date : '1/2/2222',
        txt_county : 'india',
    },
]